# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='unknownuser.jpg', upload_to='account'),
        ),
    ]
