# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20171108_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='account/unknownuser.jpg', upload_to='account/'),
        ),
    ]
