# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20171109_1732'),
        ('account', '0006_auto_20171113_2254'),
    ]

    operations = [
    ]
