# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 16:14
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_merge_20171114_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='account/user-sidebar.png', upload_to=account.models.unique_profile_name),
        ),
    ]
