# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0003_recievemail_sentmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='recievemail',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sentmail',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
