# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0004_auto_20171122_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recievemail',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentmail',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
