# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171114_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='category',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='description',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='price',
        ),
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
