# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
