# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20171122_0936'),
        ('posts', '0009_comments_user'),
    ]

    operations = [
    ]
