# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20171122_1119'),
        ('posts', '0010_merge_20171122_1417'),
    ]

    operations = [
    ]
