# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_merge_20171123_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(default='posts/no_image_available.jpg', upload_to=posts.models.unique_post_name),
        ),
    ]
