# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_merge_20171123_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
