# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_posts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(default='This is a test description. I hope it is long enough.', max_length=255),
            preserve_default=False,
        ),
    ]
